import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { authOptions } from "@/utils/auth";
import { getServerSession } from "next-auth";
import SignOutButton from "./SignOutButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-gray-900`}
      >
        <div className="min-h-screen">
          <header className="border-b bg-white">
            <div className="mx-auto max-w-5xl px-4 py-4 flex items-center justify-between">
              <h1 className="text-lg font-semibold">Tutor Tools</h1>
              <nav className="text-sm flex items-center gap-2">
                {session ? (
                  <>
                    <a href="/" className="hover:underline">Dashboard</a>
                    <span className="px-2">·</span>
                    <a href="/students" className="hover:underline">Students</a>
                    <span className="px-2">·</span>
                  </>
                ) : null}
                {!session ? (
                  <div className="flex items-center gap-2">
                    <a href="/signin" className="rounded-md border px-3 py-1.5 hover:bg-gray-50">Log in</a>
                    <a href="/signup" className="rounded-md bg-black text-white px-3 py-1.5 hover:opacity-90">Sign up</a>
                  </div>
                ) : (
                  <SignOutButton />
                )}
              </nav>
            </div>
          </header>
          <main className="mx-auto max-w-5xl px-4 py-6">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
